### ISSUE TITLE
docs not available

### ISSUE THREAD

**Issue by dashed** [rust-datetime/zoneinfo-parse#1]
Hi!

Kudos for this library. Working great for my needs.

I'd like to give a heads up that the rust docs seems to be giving 404 errors: https://datetime.rustdocs.org/zoneinfo_parse/index.html

/cc @ogham

**Comment by ogham** [comment]
Glad you're enjoying the library. I wish I had more time to work on it these days...

I updated the link to use docs.rs — the docs should be available again soon.
