### ISSUE TITLE
Negative offsets with zero hours are not handled correctly

### ISSUE THREAD

**Issue by djzin** [rust-datetime/zoneinfo-parse#5]
The library assumes that if an offset is negative, then this will be stored in the hours. However this gives a wrong offset for e.g. London pre-1847 where the clock was just 1min 15 seconds behind UTC - the library reports a positive offset.
## To reproduce

``` rust
extern crate zoneinfo_parse;
use zoneinfo_parse::line::Line;
use zoneinfo_parse::line::TimeSpec;

static LINE : &'static str = "Zone    Europe/London   -0:01:15 -  LMT 1847 Dec  1  0:00s";

fn main() {
    let line = Line::from_str(LINE).unwrap();
    if let Line::Zone(zone) = line {
        assert_eq!(zone.info.utc_offset, TimeSpec::HoursMinutesSeconds(0, -1, -15));
    }
}
```

Not sure how this should be represented internally, but it is wrong at the moment

**Comment by ogham** [comment]
This was _also_ also fixed by #6.
